include ../lilypond.mk

all: pachelbel-canon-variation-score.pdf
all: pachelbel-canon-variation-vln1.pdf
all: pachelbel-canon-variation-vln2.pdf
all: pachelbel-canon-variation-vlns.pdf

# include dependencies
pachelbel-canon-variation-score.pdf: pachelbel-canon-variation.ly
pachelbel-canon-variation-vln1.pdf: pachelbel-canon-variation.ly
pachelbel-canon-variation-vln2.pdf: pachelbel-canon-variation.ly
pachelbel-canon-variation-vlns.pdf: pachelbel-canon-variation.ly

